# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackover_tickets', '0003_ticket_accessed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='payed',
            new_name='paid',
        ),
    ]
