# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackover_tickets', '0004_auto_20160827_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiseorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
