# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackover_tickets', '0005_merchandiseorder_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiseorder',
            name='accessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='merchandiseorder',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderrelation',
            name='amount',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='orderrelation',
            name='merchandise',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hackover_tickets.Merchandise'),
        ),
        migrations.AlterField(
            model_name='orderrelation',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hackover_tickets.MerchandiseOrder'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hackover_tickets.TicketType'),
        ),
    ]
