# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackover_tickets', '0006_auto_20160828_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiseorder',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
